#!/usr/bin/python

def primes(n):
    """ Returns  a list of primes < n """
    sieve = [True] * n
    for i in xrange(3,int(n**0.5)+1,2):
        if sieve[i]:
            sieve[i*i::2*i]=[False]*((n-i*i-1)/(2*i)+1)
    return [2] + [i for i in xrange(3,n,2) if sieve[i]]

p = primes(1000000)
print("PRIME")
nums = []

complete = False

for i in range(1,1000):
	nums.append(2*i*i)
print("NUMS")
for i in range(3, 10001, 2):
	complete = False
	if i not in p:
		for j in nums:
			if i>j and (i-j) in p:
				complete = True
		if not complete:
			print(i)

print("DONE")